### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Tsnxx** [LiamLian0727/WaterMask#3]
/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
2024-03-24 01:05:50,342 - mmdet - INFO - Epoch [19][50/1969]    lr: 2.500e-03, eta: 10:00:24, time: 1.138, data_time: 0.074, memory: 10150, loss_rpn_cls: 0.0254, loss_rpn_bbox: 0.0366, loss_cls: 0.2123, acc: 92.0410, loss_bbox: 0.2301, loss_lcf: 0.5930, loss: 1.0974, grad_norm: 5.5646
2024-03-24 01:06:41,319 - mmdet - INFO - Epoch [19][100/1969]   lr: 2.500e-03, eta: 9:59:34, time: 1.020, data_time: 0.022, memory: 10150, loss_rpn_cls: 0.0273, loss_rpn_bbox: 0.0299, loss_cls: 0.2023, acc: 92.6719, loss_bbox: 0.2234, loss_lcf: 0.5742, loss: 1.0570, grad_norm: 5.8542
2024-03-24 01:07:31,510 - mmdet - INFO - Epoch [19][150/1969]   lr: 2.500e-03, eta: 9:58:42, time: 1.004, data_time: 0.021, memory: 10150, loss_rpn_cls: 0.0304, loss_rpn_bbox: 0.0310, loss_cls: 0.2012, acc: 92.8457, loss_bbox: 0.2072, loss_lcf: 0.5775, loss: 1.0473, grad_norm: 5.5333
2024-03-24 01:08:28,286 - mmdet - INFO - Epoch [19][200/1969]   lr: 2.500e-03, eta: 9:57:57, time: 1.136, data_time: 0.029, memory: 10150, loss_rpn_cls: 0.0442, loss_rpn_bbox: 0.0463, loss_cls: 0.2288, acc: 91.2773, loss_bbox: 0.2531, loss_lcf: 0.6156, loss: 1.1881, grad_norm: 5.4719
2024-03-24 01:09:19,922 - mmdet - INFO - Epoch [19][250/1969]   lr: 2.500e-03, eta: 9:57:07, time: 1.033, data_time: 0.023, memory: 10150, loss_rpn_cls: 0.0324, loss_rpn_bbox: 0.0332, loss_cls: 0.1940, acc: 92.7637, loss_bbox: 0.2164, loss_lcf: 0.5783, loss: 1.0542, grad_norm: 5.2549
2024-03-24 01:10:14,178 - mmdet - INFO - Epoch [19][300/1969]   lr: 2.500e-03, eta: 9:56:19, time: 1.085, data_time: 0.024, memory: 10150, loss_rpn_cls: 0.0281, loss_rpn_bbox: 0.0361, loss_cls: 0.1894, acc: 92.9629, loss_bbox: 0.2161, loss_lcf: 0.5405, loss: 1.0102, grad_norm: 5.4155
2024-03-24 01:11:06,850 - mmdet - INFO - Epoch [19][350/1969]   lr: 2.500e-03, eta: 9:55:30, time: 1.053, data_time: 0.024, memory: 10150, loss_rpn_cls: 0.0453, loss_rpn_bbox: 0.0375, loss_cls: 0.2217, acc: 91.7793, loss_bbox: 0.2417, loss_lcf: 0.5768, loss: 1.1230, grad_norm: 5.9534
2024-03-24 01:11:59,516 - mmdet - INFO - Epoch [19][400/1969]   lr: 2.500e-03, eta: 9:54:41, time: 1.053, data_time: 0.030, memory: 10150, loss_rpn_cls: 0.0343, loss_rpn_bbox: 0.0368, loss_cls: 0.2023, acc: 92.6113, loss_bbox: 0.2265, loss_lcf: 0.5760, loss: 1.0760, grad_norm: 5.3109
2024-03-24 01:12:52,291 - mmdet - INFO - Epoch [19][450/1969]   lr: 2.500e-03, eta: 9:53:52, time: 1.056, data_time: 0.028, memory: 10150, loss_rpn_cls: 0.0423, loss_rpn_bbox: 0.0459, loss_cls: 0.2104, acc: 92.2891, loss_bbox: 0.2335, loss_lcf: 0.6015, loss: 1.1336, grad_norm: 5.2622
2024-03-24 01:13:41,783 - mmdet - INFO - Epoch [19][500/1969]   lr: 2.500e-03, eta: 9:52:59, time: 0.990, data_time: 0.031, memory: 10150, loss_rpn_cls: 0.0334, loss_rpn_bbox: 0.0379, loss_cls: 0.1910, acc: 93.1699, loss_bbox: 0.2022, loss_lcf: 0.5936, loss: 1.0580, grad_norm: 5.3891
2024-03-24 01:14:35,718 - mmdet - INFO - Epoch [19][550/1969]   lr: 2.500e-03, eta: 9:52:11, time: 1.079, data_time: 0.034, memory: 10150, loss_rpn_cls: 0.0328, loss_rpn_bbox: 0.0387, loss_cls: 0.2080, acc: 92.1113, loss_bbox: 0.2297, loss_lcf: 0.5766, loss: 1.0858, grad_norm: 5.4462
2024-03-24 01:15:29,172 - mmdet - INFO - Epoch [19][600/1969]   lr: 2.500e-03, eta: 9:51:23, time: 1.069, data_time: 0.025, memory: 10150, loss_rpn_cls: 0.0303, loss_rpn_bbox: 0.0357, loss_cls: 0.2054, acc: 92.7969, loss_bbox: 0.2104, loss_lcf: 0.5421, loss: 1.0239, grad_norm: 5.5983
2024-03-24 01:16:22,486 - mmdet - INFO - Epoch [19][650/1969]   lr: 2.500e-03, eta: 9:50:34, time: 1.066, data_time: 0.024, memory: 10150, loss_rpn_cls: 0.0277, loss_rpn_bbox: 0.0307, loss_cls: 0.2045, acc: 92.7617, loss_bbox: 0.2244, loss_lcf: 0.5582, loss: 1.0454, grad_norm: 5.4633
2024-03-24 01:17:17,787 - mmdet - INFO - Epoch [19][700/1969]   lr: 2.500e-03, eta: 9:49:48, time: 1.106, data_time: 0.030, memory: 10150, loss_rpn_cls: 0.0341, loss_rpn_bbox: 0.0366, loss_cls: 0.2166, acc: 92.2344, loss_bbox: 0.2377, loss_lcf: 0.5522, loss: 1.0773, grad_norm: 5.4867
2024-03-24 01:18:11,169 - mmdet - INFO - Epoch [19][750/1969]   lr: 2.500e-03, eta: 9:48:59, time: 1.068, data_time: 0.021, memory: 10150, loss_rpn_cls: 0.0274, loss_rpn_bbox: 0.0329, loss_cls: 0.2145, acc: 92.4082, loss_bbox: 0.2300, loss_lcf: 0.5653, loss: 1.0701, grad_norm: 5.2619
2024-03-24 01:19:02,617 - mmdet - INFO - Epoch [19][800/1969]   lr: 2.500e-03, eta: 9:48:09, time: 1.029, data_time: 0.023, memory: 10150, loss_rpn_cls: 0.0224, loss_rpn_bbox: 0.0354, loss_cls: 0.1862, acc: 93.4688, loss_bbox: 0.1964, loss_lcf: 0.5628, loss: 1.0031, grad_norm: 5.4660
2024-03-24 01:19:54,787 - mmdet - INFO - Epoch [19][850/1969]   lr: 2.500e-03, eta: 9:47:19, time: 1.043, data_time: 0.033, memory: 10150, loss_rpn_cls: 0.0353, loss_rpn_bbox: 0.0392, loss_cls: 0.2013, acc: 92.8926, loss_bbox: 0.2126, loss_lcf: 0.5537, loss: 1.0421, grad_norm: 5.3490
2024-03-24 01:20:49,879 - mmdet - INFO - Epoch [19][900/1969]   lr: 2.500e-03, eta: 9:46:32, time: 1.102, data_time: 0.025, memory: 10150, loss_rpn_cls: 0.0308, loss_rpn_bbox: 0.0387, loss_cls: 0.1995, acc: 92.8965, loss_bbox: 0.2166, loss_lcf: 0.5489, loss: 1.0345, grad_norm: 5.3142
2024-03-24 01:21:43,683 - mmdet - INFO - Epoch [19][950/1969]   lr: 2.500e-03, eta: 9:45:44, time: 1.076, data_time: 0.023, memory: 10150, loss_rpn_cls: 0.0262, loss_rpn_bbox: 0.0329, loss_cls: 0.2065, acc: 92.5273, loss_bbox: 0.2172, loss_lcf: 0.5654, loss: 1.0482, grad_norm: 5.7166
2024-03-24 01:22:33,251 - mmdet - INFO - Epoch [19][1000/1969]  lr: 2.500e-03, eta: 9:44:51, time: 0.991, data_time: 0.026, memory: 10150, loss_rpn_cls: 0.0271, loss_rpn_bbox: 0.0321, loss_cls: 0.2004, acc: 92.5938, loss_bbox: 0.2092, loss_lcf: 0.5625, loss: 1.0313, grad_norm: 4.9155
2024-03-24 01:23:24,049 - mmdet - INFO - Epoch [19][1050/1969]  lr: 2.500e-03, eta: 9:44:00, time: 1.016, data_time: 0.028, memory: 10150, loss_rpn_cls: 0.0348, loss_rpn_bbox: 0.0348, loss_cls: 0.2059, acc: 92.2852, loss_bbox: 0.2146, loss_lcf: 0.6045, loss: 1.0946, grad_norm: 5.2371
2024-03-24 01:24:15,925 - mmdet - INFO - Epoch [19][1100/1969]  lr: 2.500e-03, eta: 9:43:10, time: 1.038, data_time: 0.023, memory: 10150, loss_rpn_cls: 0.0300, loss_rpn_bbox: 0.0330, loss_cls: 0.2165, acc: 91.9414, loss_bbox: 0.2305, loss_lcf: 0.5868, loss: 1.0969, grad_norm: 5.8238
2024-03-24 01:25:08,579 - mmdet - INFO - Epoch [19][1150/1969]  lr: 2.500e-03, eta: 9:42:21, time: 1.053, data_time: 0.025, memory: 10150, loss_rpn_cls: 0.0429, loss_rpn_bbox: 0.0411, loss_cls: 0.2338, acc: 91.6230, loss_bbox: 0.2399, loss_lcf: 0.5972, loss: 1.1549, grad_norm: 5.6899
2024-03-24 01:26:01,868 - mmdet - INFO - Epoch [19][1200/1969]  lr: 2.500e-03, eta: 9:41:32, time: 1.066, data_time: 0.030, memory: 10150, loss_rpn_cls: 0.0459, loss_rpn_bbox: 0.0454, loss_cls: 0.2095, acc: 92.2637, loss_bbox: 0.2250, loss_lcf: 0.5778, loss: 1.1035, grad_norm: 5.6925
2024-03-24 01:26:51,579 - mmdet - INFO - Epoch [19][1250/1969]  lr: 2.500e-03, eta: 9:40:40, time: 0.994, data_time: 0.022, memory: 10150, loss_rpn_cls: 0.0290, loss_rpn_bbox: 0.0355, loss_cls: 0.1939, acc: 92.7188, loss_bbox: 0.2167, loss_lcf: 0.5213, loss: 0.9963, grad_norm: 5.6672
2024-03-24 01:27:47,085 - mmdet - INFO - Epoch [19][1300/1969]  lr: 2.500e-03, eta: 9:39:53, time: 1.110, data_time: 0.029, memory: 10150, loss_rpn_cls: 0.0369, loss_rpn_bbox: 0.0365, loss_cls: 0.2350, acc: 91.4180, loss_bbox: 0.2677, loss_lcf: 0.6013, loss: 1.1775, grad_norm: 5.5364
2024-03-24 01:28:38,910 - mmdet - INFO - Epoch [19][1350/1969]  lr: 2.500e-03, eta: 9:39:03, time: 1.037, data_time: 0.024, memory: 10150, loss_rpn_cls: 0.0327, loss_rpn_bbox: 0.0349, loss_cls: 0.2043, acc: 92.5059, loss_bbox: 0.2216, loss_lcf: 0.5837, loss: 1.0773, grad_norm: 5.6471
2024-03-24 01:29:31,320 - mmdet - INFO - Epoch [19][1400/1969]  lr: 2.500e-03, eta: 9:38:14, time: 1.048, data_time: 0.033, memory: 10150, loss_rpn_cls: 0.0366, loss_rpn_bbox: 0.0392, loss_cls: 0.2277, acc: 91.8828, loss_bbox: 0.2279, loss_lcf: 0.5553, loss: 1.0866, grad_norm: 5.5198
2024-03-24 01:30:26,934 - mmdet - INFO - Epoch [19][1450/1969]  lr: 2.500e-03, eta: 9:37:27, time: 1.112, data_time: 0.027, memory: 10150, loss_rpn_cls: 0.0462, loss_rpn_bbox: 0.0425, loss_cls: 0.2458, acc: 91.3984, loss_bbox: 0.2529, loss_lcf: 0.6186, loss: 1.2060, grad_norm: 5.3996
2024-03-24 01:31:19,543 - mmdet - INFO - Epoch [19][1500/1969]  lr: 2.500e-03, eta: 9:36:37, time: 1.052, data_time: 0.020, memory: 10150, loss_rpn_cls: 0.0297, loss_rpn_bbox: 0.0361, loss_cls: 0.2002, acc: 92.6406, loss_bbox: 0.2439, loss_lcf: 0.5708, loss: 1.0807, grad_norm: 5.7786
2024-03-24 01:32:17,616 - mmdet - INFO - Epoch [19][1550/1969]  lr: 2.500e-03, eta: 9:35:53, time: 1.161, data_time: 0.026, memory: 10150, loss_rpn_cls: 0.0380, loss_rpn_bbox: 0.0435, loss_cls: 0.2475, acc: 90.9922, loss_bbox: 0.2727, loss_lcf: 0.6313, loss: 1.2330, grad_norm: 5.5360
2024-03-24 01:33:07,800 - mmdet - INFO - Epoch [19][1600/1969]  lr: 2.500e-03, eta: 9:35:01, time: 1.004, data_time: 0.026, memory: 10150, loss_rpn_cls: 0.0317, loss_rpn_bbox: 0.0310, loss_cls: 0.2056, acc: 92.7676, loss_bbox: 0.2065, loss_lcf: 0.5643, loss: 1.0392, grad_norm: 5.4308
2024-03-24 01:34:00,434 - mmdet - INFO - Epoch [19][1650/1969]  lr: 2.500e-03, eta: 9:34:12, time: 1.053, data_time: 0.031, memory: 10150, loss_rpn_cls: 0.0340, loss_rpn_bbox: 0.0388, loss_cls: 0.2129, acc: 92.4004, loss_bbox: 0.2204, loss_lcf: 0.5821, loss: 1.0883, grad_norm: 5.5693
2024-03-24 01:34:51,850 - mmdet - INFO - Epoch [19][1700/1969]  lr: 2.500e-03, eta: 9:33:21, time: 1.028, data_time: 0.026, memory: 10150, loss_rpn_cls: 0.0305, loss_rpn_bbox: 0.0352, loss_cls: 0.2059, acc: 92.7266, loss_bbox: 0.2242, loss_lcf: 0.5630, loss: 1.0590, grad_norm: 5.2287
2024-03-24 01:35:48,940 - mmdet - INFO - Epoch [19][1750/1969]  lr: 2.500e-03, eta: 9:32:36, time: 1.142, data_time: 0.028, memory: 10150, loss_rpn_cls: 0.0315, loss_rpn_bbox: 0.0372, loss_cls: 0.2225, acc: 91.9238, loss_bbox: 0.2409, loss_lcf: 0.5747, loss: 1.1068, grad_norm: 5.6253
2024-03-24 01:36:44,627 - mmdet - INFO - Epoch [19][1800/1969]  lr: 2.500e-03, eta: 9:31:49, time: 1.114, data_time: 0.025, memory: 10150, loss_rpn_cls: 0.0363, loss_rpn_bbox: 0.0344, loss_cls: 0.2152, acc: 92.1406, loss_bbox: 0.2381, loss_lcf: 0.5954, loss: 1.1194, grad_norm: 5.4466
2024-03-24 01:37:32,505 - mmdet - INFO - Epoch [19][1850/1969]  lr: 2.500e-03, eta: 9:30:55, time: 0.958, data_time: 0.019, memory: 10150, loss_rpn_cls: 0.0288, loss_rpn_bbox: 0.0286, loss_cls: 0.1993, acc: 92.8555, loss_bbox: 0.2017, loss_lcf: 0.5290, loss: 0.9875, grad_norm: 5.3237
2024-03-24 01:38:22,337 - mmdet - INFO - Epoch [19][1900/1969]  lr: 2.500e-03, eta: 9:30:03, time: 0.997, data_time: 0.020, memory: 10150, loss_rpn_cls: 0.0293, loss_rpn_bbox: 0.0331, loss_cls: 0.1848, acc: 93.3340, loss_bbox: 0.2020, loss_lcf: 0.5769, loss: 1.0261, grad_norm: 5.5363
2024-03-24 01:39:13,610 - mmdet - INFO - Epoch [19][1950/1969]  lr: 2.500e-03, eta: 9:29:13, time: 1.025, data_time: 0.022, memory: 10150, loss_rpn_cls: 0.0293, loss_rpn_bbox: 0.0345, loss_cls: 0.2079, acc: 92.6875, loss_bbox: 0.2246, loss_lcf: 0.5902, loss: 1.0864, grad_norm: 5.3358
2024-03-24 01:40:26,333 - mmdet - INFO - Epoch [20][50/1969]    lr: 2.500e-03, eta: 9:27:44, time: 1.006, data_time: 0.071, memory: 10150, loss_rpn_cls: 0.0325, loss_rpn_bbox: 0.0299, loss_cls: 0.1864, acc: 93.2402, loss_bbox: 0.1895, loss_lcf: 0.5486, loss: 0.9870, grad_norm: 5.0287
2024-03-24 01:41:21,346 - mmdet - INFO - Epoch [20][100/1969]   lr: 2.500e-03, eta: 9:26:57, time: 1.100, data_time: 0.035, memory: 10150, loss_rpn_cls: 0.0299, loss_rpn_bbox: 0.0343, loss_cls: 0.1842, acc: 93.0762, loss_bbox: 0.2078, loss_lcf: 0.5509, loss: 1.0071, grad_norm: 5.0761
2024-03-24 01:42:15,135 - mmdet - INFO - Epoch [20][150/1969]   lr: 2.500e-03, eta: 9:26:08, time: 1.076, data_time: 0.027, memory: 10150, loss_rpn_cls: 0.0276, loss_rpn_bbox: 0.0365, loss_cls: 0.2030, acc: 92.4238, loss_bbox: 0.2219, loss_lcf: 0.5654, loss: 1.0544, grad_norm: 5.2354
2024-03-24 01:43:08,245 - mmdet - INFO - Epoch [20][200/1969]   lr: 2.500e-03, eta: 9:25:19, time: 1.062, data_time: 0.031, memory: 10150, loss_rpn_cls: 0.0376, loss_rpn_bbox: 0.0397, loss_cls: 0.2149, acc: 92.4004, loss_bbox: 0.2238, loss_lcf: 0.5886, loss: 1.1046, grad_norm: 5.2252
2024-03-24 01:44:00,989 - mmdet - INFO - Epoch [20][250/1969]   lr: 2.500e-03, eta: 9:24:30, time: 1.055, data_time: 0.027, memory: 10150, loss_rpn_cls: 0.0219, loss_rpn_bbox: 0.0323, loss_cls: 0.1857, acc: 93.0059, loss_bbox: 0.2078, loss_lcf: 0.5438, loss: 0.9914, grad_norm: 5.7384
2024-03-24 01:44:58,226 - mmdet - INFO - Epoch [20][300/1969]   lr: 2.500e-03, eta: 9:23:44, time: 1.145, data_time: 0.028, memory: 10150, loss_rpn_cls: 0.0269, loss_rpn_bbox: 0.0363, loss_cls: 0.2231, acc: 91.6270, loss_bbox: 0.2552, loss_lcf: 0.5744, loss: 1.1159, grad_norm: 5.6827
2024-03-24 01:45:53,725 - mmdet - INFO - Epoch [20][350/1969]   lr: 2.500e-03, eta: 9:22:57, time: 1.110, data_time: 0.024, memory: 10150, loss_rpn_cls: 0.0351, loss_rpn_bbox: 0.0356, loss_cls: 0.2357, acc: 90.9863, loss_bbox: 0.2640, loss_lcf: 0.5781, loss: 1.1486, grad_norm: 5.5181
Traceback (most recent call last):
  File "tools/train.py", line 243, in <module>
    main()
  File "tools/train.py", line 239, in main
    meta=meta)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/roi_heads/standard_roi_head.py", line 113, in forward_train
    gt_masks, img_metas)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/roi_heads/water_roi_head.py", line 40, in _mask_forward_train
    mask_results = self._mask_forward(x, pos_rois, torch.cat(pos_labels))
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/roi_heads/water_roi_head.py", line 51, in _mask_forward
    stage_lcf_preds = self.mask_head(ins_feats, x[0], rois, roi_labels)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/roi_heads/mask_heads/water_mask_head.py", line 324, in forward
    lcf_feats, lcf_logits, gff_feat, rois, upsample_flag)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/btbu/gt/tsn/WaterMask-master/mmdet/models/roi_heads/mask_heads/water_mask_head.py", line 188, in forward
    ins_gff_feats = self.gff_roi_extractor(gff_feat, rois)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/btbu/Anaconda/enter/envs/watermask/lib/python3.7/site-packages/mmcv/ops/point_sample.py", line 325, in forward
    point_feats = torch.cat(point_feats, dim=0)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:18433 [kernel]
CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:26496 [kernel]
QuantizedCPU: registered at aten/src/ATen/RegisterQuantizedCPU.cpp:1068 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_3.cpp:11560 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

**Comment by LiamLian0727** [comment]
This is mainly caused by the fact that the network doesn't get any result at a particular inference, you can refer to the solution in this [issue](https://github.com/LiamLian0727/WaterMask/issues/1).
